### ISSUE TITLE
Oprette vagtplan

### ISSUE THREAD

**Issue by Geofery** [Dad-inc-appendchild/Kino#26]
### User story

- [X] `epic`

### Story

Kunden ønsker mulighed for at oprette en vagtplan. 

### Acceptance Criteria

Kunden har en vagtplan så de kan se hvem der skal arbejde og hvornår. 

### Addition

- [ ] Oprette ansatte på hjemmesiden
- [ ] Oprette ansatte i databasen
- [ ] Tilføje ansatte til en enkelt dag
- [ ] Visuel vagtplan 

### Priority

- [ ] `high`
- [ ] `medium`
- [x] `low`
- [ ] `unprioritized`
